services:
  keycloak:
    command: start-dev --import-realm
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KK_TO_RMQ_URL=rabbit
      - KK_TO_RMQ_USERNAME=guest
      - KK_TO_RMQ_PASSWORD=guest
      - KK_TO_RMQ_VHOST=/
    volumes:
      - keycloak_data:/opt/keycloak/data
      - ../keycloak/realm.json:/opt/keycloak/data/import/realm.json
    ports:
      - 8080:8080

  postgres:
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=road_safety
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5445:5432

  rabbit:
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  keycloak_data:
  postgres_data: